config/routes.rb
Rails.application.routes.draw do  
 
  

  # main dashboards
  get                  'admin/dashboard' => 'dashboards#index'

  # sessions
  get                           "logout" => "sessions#destroy"
  get                       'ncrs/login' => 'sessions#new'
  get                     'ncrs/sign_up' => 'admins#new'

resources :sessions
resources :admins
resources :password_resets
end

app/models/admin.rb
class Admin < ActiveRecord::Base 

	attr_accessor :password
	before_save :encrypt_password
	after_save :clear_password  
	before_create { generate_token(:auth_token)}

  	validates_presence_of :name
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, :uniqueness => true, format: { with: VALID_EMAIL_REGEX }

	validates :password, :confirmation => true
	validates_presence_of :password, :on => :create
	validates_length_of :password, :in => 6..20, :on => :create

	def self.authenticate(email,password)
		admin = find_by_email(email)
		if admin && admin.password_hash == BCrypt::Engine.hash_secret(password, admin.password_salt)
			admin
		else	
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end

	def clear_password
		self.password = nil
	end

	def send_password_reset
	  generate_token(:password_reset_token)
	  self.password_reset_sent_at = Time.zone.now
	  save!
	  AdminMailer.password_reset(self).deliver_now
	end 

	def generate_token(column)
	  begin
	    self[column] = SecureRandom.urlsafe_base64
	  end while Admin.exists?(column => self[column])
	end 


end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  
  def new
  	@admin = Admin.new
  end  
  
  def create
  	@admin = Admin.new(admin_params)
	  if @admin.save 
	    redirect_to ncrs_login_path, :notice => "Signed up!"
	  else
	    render "new"
	  end
  end

  private

  def admin_params 
  	params.require(:admin).permit(:email, :name, :password, :password_confirmation)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user  

  	def current_user
       	@current_user ||= Admin.find_by_auth_token(cookies[:auth_token]) if cookies[:auth_token]
  	end 

   	def require_user
   		redirect_to ncrs_login_url, :notice => "Please login first" unless current_user
   	end 

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :require_user  
  
  def index
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	skip_before_action :require_user

	def new 
	end

    def create
  	  @admin = Admin.find_by_email(params[:email]) 
  	  	@admin.send_password_reset if @admin
  	  	redirect_to ncrs_login_url, :notice => "Email sent with password reset instructions"  
    end

	def edit
	   @admin = Admin.find_by_password_reset_token!(params[:id])
	end

	def update
	  @admin = Admin.find_by_password_reset_token!(params[:id])
	  if @admin.password_reset_sent_at < 2.hours.ago
	    redirect_to new_password_reset_path, :alert => "Password reset has expired."
	  elsif @admin.update_attributes(user_params)
	    redirect_to ncrs_login_url, :notice => "Password has been reset!"
	  else
	    render :edit
	  end
	end

  	def user_params
    	params.require(:admin).permit(:email, :password, :password_confirmation)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
  before_action :current_user

  def new
  end

  	def create
	  admin = Admin.authenticate(params[:email], params[:password])
	  if admin
	  	cookies.permanent[:auth_token] = admin.auth_token 
	    redirect_to "/admin/dashboard"
	  else
	    redirect_to ncrs_login_path, :notice => "Invalid email or password"
	  end
	end

	def destroy
	  cookies.delete(:auth_token)
	  redirect_to ncrs_login_path, :notice => "Logged out!"
	end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admins/new.html.erb
<div class="container">
  <div class="row">
    <div class="col s3"></div>
    <div class="col s6">
      <h1>Sign Up</h1>

    <% if @admin.errors.any? %>
      <div class="error_messages"> 
        <ul>
          <% for message in @admin.errors.full_messages %>
            <li class="red-text"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_for @admin do |f| %>
      <p>
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.label :email %><br />
        <%= f.text_field :email %>
      </p>
      <p>
        <%= f.label :password %><br />
        <%= f.password_field :password %>
      </p>
      <p>
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation %>
      </p>
      <p class="waves-effect btn blue"><%= f.submit %></p>
    <% end %>
    	<%= link_to "Login", ncrs_login_path%>
    </div>
    <div class="col s3"></div>
  </div>
</div>

app/views/dashboards/index.html.erb
<% provide(:title, "Main Dashboard |") %>
<%= render "layouts/navbar_admin" %>
 

<div class="container">
  <div class="section">
    <div class="row">
      <h3 class="center-align"></h3>
         <div class="row">
          <div class="col s12 m6">
            <div class="card blue darken-2 hoverable">
              <div class="card-content white-text">
                <span class="card-title center"><h1>CEBU</h1></span>
                <p><%= material_icon.place %> 802A Keppel Center along Samar Loop cor.
                  Cardinal Rosales Avenue, Cebu Business Park,
                  Cebu City - 6000 </p>
                <br>
                <p><%= material_icon.fingerprint %> teacher here</p>
              </div>
              <div class="card-action center">
                <%= link_to "Go to Cebu Dashboard", '#' %>
                <!-- cebu dashboard -->
              </div>
            </div>
          </div>
          <div class="col s12 m6">
            <div class="card blue darken-2 hoverable">
              <div class="card-content white-text">
                <span class="card-title center"><h1>MANILA</h1></span>
                <p><%= material_icon.place %> Unit 902A Philippine Stock Exchange Center
                    East Tower Exchange Road, Ortigas Center,
                    Pasig City - 1605  </p>
                <br>
                <p><%= material_icon.fingerprint %> teacher here</p>
              </div>
              <div class="card-action center">
                <%= link_to "Go to Manila Dashboard", '#' %> 
                <!-- manila dashboard -->
              </div>
            </div>
          </div>
        </div>
    </div>
  </div> 
</div>

app/views/layouts/_navbar_admin.html.erb
<div class="navbar-fixed">
    <nav class="blue darken-2" role="navigation">
        <div class="nav-wrapper container">
          <%= link_to image_tag("nihongo class.png", :alt => "Study Nihongo", :class => "img-responsive"), '#', class: "brand-logo" %>  

            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><%= link_to "Main Dashboard", admin_dashboard_path %></li>  
                <!-- inquiries path -->
                <!-- articles path -->
                <!-- teachers path -->
                <!-- galleries path -->
                <!-- payment path -->  
                <li><%= link_to material_icon.settings_power, logout_path%></li> 
            </ul>

          <ul id="slide-out" class="side-nav">
            <li>
                <div class="userView">
                  <%= image_tag("bg.png", :alt => "Study Nihongo", :class => "background")  %> 
                  <div class="center-align">
                    <a href="#!user"><%= image_tag("joy.jpg", :alt => "Study Nihongo", :class => "circle responsive-img", :style => "margin: auto")  %></a>
                  </div>  
                  <a href="#!name"><span class="white-text name"><%= current_user.name %></span></a>
                  <a href="#!email"><span class="white-text email"><%= current_user.email %></span></a>
                </div>
            </li>  
            <li><%= link_to "Dashboard", admin_dashboard_path %></li>  
                <!-- inquiries path -->
                <!-- articles path -->
                <!-- teachers path -->
                <!-- galleries path -->
                <!-- payment path --> 
            <li><%= link_to "Logout?", logout_path %></li> 
            <li><div class="divider"></div></li>

            <li><a class="subheader center-align"><small class="">Nihongo Class Reservation System </small></a></li>  
          </ul> 
          <a href="#" data-activates="slide-out" class="button-collapse"><%= material_icon.menu %></a>
        </div>
    </nav>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title)%> Studynihongo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
	<body>

		<%= yield %>

	</body>
		<script type="text/javascript">
			$(document).ready(function(){ 
			    $(".button-collapse").sideNav({

			      menuWidth: 300, // Default is 240
			      edge: 'right', // Choose the horizontal origin
			      closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor

			    }); 
			    $('.modal-trigger').leanModal(); 
			    $('.scrollspy').scrollSpy();   
			    $('.tooltipped').tooltip({delay: 50}); 
			})
		</script>
</html>

app/views/partials/_check.html.erb
<div class="divider"></div>
<div class="section orange darken-2 white-text" style="margin-bottom: -20px">
	<h5 class="center">Check out active schedules for <%= link_to "Cebu", cebu_schedules_path, class: "white-text waves-effect teal btn" %> and <%= link_to "Manila", manila_schedules_path, class: "white-text waves-effect teal btn" %>!</h5> 
</div>

app/views/partials/_notification.html.erb
<div class="row">
	<div class="col s4"></div>
	<div class="col s4"> 
		<% flash.each do |name, msg| %>
		  <%= content_tag :div, msg, :id => "flash_#{name}", :class => "center-align orange-text"%>
		<% end %> 
	</div>
	<div class="col s4"></div>
</div>

app/views/password_resets/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col s3"></div>
		<div class="col s6">
			<div class="center-align">
				<h3>Update your password</h3> 
			</div>
			<%= form_for @admin, :url => password_reset_path(params[:id]) do |f| %>
			  <% if @admin.errors.any? %>
			    <div class="error_messages">
			      <h2>Form is invalid</h2>
			      <ul>
			        <% for message in @admin.errors.full_messages %>
			          <li><%= message %></li>
			        <% end %>
			      </ul>
			    </div>
			  <% end %>
			  <div class="field">
			    <%= f.label :password %>
			    <%= f.password_field :password %>
			  </div>
			  <div class="field">
			    <%= f.label :password_confirmation %>
			    <%= f.password_field :password_confirmation %>
			  </div>
			  <div class="center"><%= f.submit "Update Password", class: "waves-effect btn blue" %></div>
			<% end %>
		</div>
		<div class="col s3"></div>
	</div>
</div>

app/views/password_resets/new.html.erb
<div class="container">
	<div class="row">
		<div class="col s3"></div>
		<div class="col s6">
			<h1>Reset Password</h1>

			<%= form_tag password_resets_path, :method => :post do %>
			  <div class="field">
			    <%= label_tag :email %>
			    <%= text_field_tag :email, params[:email] %>
			  </div>
			  <div class="actions center	"><%= submit_tag "Reset Password", class: "waves-effect btn blue" %></div>
			<% end %>
			
		</div>
		<div class="col s3"></div>
	</div>
</div>